# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ffba117927aa530cfbb7fd79307d1e35"
name = "ChatBot"
application_url = "https://example.com"
embedded = true
handle = "ai-chatbot-lab"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_checkouts,read_customers,read_inventory,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
